version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: nicotine-fastapi
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8002:8000
    volumes:
      - ./app:/app
      - ./clients:/app/clients
      - ${PLAYLIST_DIR}:/playlists
      - ${DB_URL}:/db
    env_file:
      - .env
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: nicotine-discord-bot
    env_file:
      - .env
    volumes:
      - ./bot:/app
      - ./clients:/app/clients
      - ${PLAYLIST_DIR}:/playlists
      - ${DB_URL}:/db/music.db


    
    
