version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: nicotine-fastapi
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8002:8000
    volumes:
      - ./app:/app
    env_file:
      - ./app/.env
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: nicotine-discord-bot
    env_file:
      - ./app/.env
    volumes:
      - ./bot:/app

    
    
