version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: nicotine-fastapi
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8002:8000
    volumes:
      - ./app:/app
      - ./clients:/app/clients
      - ./alembic:/app/alembic
      - ./bot/utils.py:/app/utils.py
      - ${PLAYLIST_DIR}:/playlists
      - ${DB_URL}:/db/music.db
      - ${MUSIC_DIR}:/music
    env_file:
      - .env
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: nicotine-discord-bot
    env_file:
      - .env
    volumes:
      - ./bot:/app
      - ./clients:/app/clients
      - ./app/models.py:/app/models.py
      - ${PLAYLIST_DIR}:/playlists
      - ${DB_URL}:/db/music.db
  postgres:
    container_name: postgres-raxdio
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-raxdio:/data/postgres
      - ./app/queries:/scripts
    ports:
      - "5433:5432"
volumes:
  postgres-raxdio: null
