"""empty message

Revision ID: 1a86dc6ea9c2
Revises: 7a12b463aa79
Create Date: 2023-04-30 09:34:24.012024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a86dc6ea9c2'
down_revision = '7a12b463aa79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('username', sa.String(), nullable=True))
    op.drop_constraint('messages_user_id_fkey', 'messages', type_='foreignkey')
    op.drop_column('messages', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('messages_user_id_fkey', 'messages', 'users', ['user_id'], ['id'])
    op.drop_column('messages', 'username')
    # ### end Alembic commands ###
