"""empty message

Revision ID: 6e7cd9b3df5b
Revises: 
Create Date: 2023-05-02 17:19:13.971103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7cd9b3df5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_songs', sa.Column('artist_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history_songs', 'artist_image')
    # ### end Alembic commands ###
